// Code generated by "mib_generator -p /usr/share/snmp/mibs/ietf -m ADSL-LINE-MIB -P adsl_line_mib". DO NOT EDIT

package adsl_line_mib

import "github.com/lazyfrosch/dslmodem_exporter/pkg/snmp"

// ADSL-LINE-MIB
const (
	// The MIB module defining objects for the management of a pair of
	// ADSL modems at each end of the ADSL line.  Each such line has
	// an entry in an ifTable which may include multiple modem lines.
	// An agent may reside at either end of the ADSL line however the
	// MIB is designed to require no management communication between
	// them beyond that inherent in the low-level ADSL line protocol.
	// The agent may monitor and control this protocol for its needs.
	// ADSL lines may support optional Fast or Interleaved channels.
	// If these are supported, additional entries corresponding to the
	// supported channels must be created in the ifTable. Thus an ADSL
	// line that supports both channels will have three entries in the
	// ifTable, one for each physical, fast, and interleaved, whose
	// ifType values are equal to adsl(94), fast(125), and
	// interleaved(124), respectively. The ifStackTable is used to
	// represent the relationship between the entries.
	// Naming Conventions:
	// Atuc -- (ATUC) modem at near (Central) end of line
	// Atur -- (ATUR) modem at Remote end of line
	// Curr -- Current
	// Prev -- Previous
	// Atn -- Attenuation
	// ES  -- Errored Second.
	// LCS -- Line Code Specific
	// Lof -- Loss of Frame
	// Lol -- Loss of Link
	// Los -- Loss of Signal
	// Lpr -- Loss of Power
	// xxxs-- interval of Seconds in which xxx occurs
	// (e.g., xxx=Lof, Los, Lpr)
	// Max -- Maximum
	// Mgn -- Margin
	// Min -- Minimum
	// Psd -- Power Spectral Density
	// Snr -- Signal to Noise Ratio
	// Tx  -- Transmit
	// Blks-- Blocks, a data unit, see
	// adslAtuXChanCrcBlockLength
	AdslMIBOid        = "1.3.6.1.2.1.10.94"
	AdslLineMibOid    = "1.3.6.1.2.1.10.94.1"
	AdslMibObjectsOid = "1.3.6.1.2.1.10.94.1.1"

	// This table includes common attributes describing
	// both ends of the line.  It is required for all ADSL
	// physical interfaces.  ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslLineTableOid = "1.3.6.1.2.1.10.94.1.1.1"

	// This table provides one row for each ATUC.
	// Each row contains the Physical Layer Parameters
	// table for that ATUC. ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslAtucPhysTableOid = "1.3.6.1.2.1.10.94.1.1.2"

	// This table provides one row for each ATUR
	// Each row contains the Physical Layer Parameters
	// table for that ATUR. ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslAturPhysTableOid = "1.3.6.1.2.1.10.94.1.1.3"

	// This table provides one row for each ATUC channel.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAtucChanTableOid = "1.3.6.1.2.1.10.94.1.1.4"

	// This table provides one row for each ATUR channel.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAturChanTableOid = "1.3.6.1.2.1.10.94.1.1.5"

	// This table provides one row for each ATUC.
	// ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslAtucPerfDataTableOid = "1.3.6.1.2.1.10.94.1.1.6"

	// This table provides one row for each ATUR.
	// ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslAturPerfDataTableOid = "1.3.6.1.2.1.10.94.1.1.7"

	// This table provides one row for each ATUC
	// performance data collection interval.
	// ADSL physical interfaces are
	// those ifEntries where ifType is equal to adsl(94).
	AdslAtucIntervalTableOid = "1.3.6.1.2.1.10.94.1.1.8"

	// This table provides one row for each ATUR
	// performance data collection interval.
	// ADSL physical interfaces are those
	// ifEntries where ifType is equal to adsl(94).
	AdslAturIntervalTableOid = "1.3.6.1.2.1.10.94.1.1.9"

	// This table provides one row for each ATUC channel.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAtucChanPerfDataTableOid = "1.3.6.1.2.1.10.94.1.1.10"

	// This table provides one row for each ATUR channel.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAturChanPerfDataTableOid = "1.3.6.1.2.1.10.94.1.1.11"

	// This table provides one row for each ATUC channel's
	// performance data collection interval.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAtucChanIntervalTableOid = "1.3.6.1.2.1.10.94.1.1.12"

	// This table provides one row for each ATUR channel's
	// performance data collection interval.
	// ADSL channel interfaces are those ifEntries
	// where ifType is equal to adslInterleave(124)
	// or adslFast(125).
	AdslAturChanIntervalTableOid = "1.3.6.1.2.1.10.94.1.1.13"

	// This table contains information on the ADSL line
	// configuration.  One entry in this table reflects a
	// profile defined by a manager which can be used to
	// configure the ADSL line.
	AdslLineConfProfileTableOid = "1.3.6.1.2.1.10.94.1.1.14"

	// This table contains information on the ADSL line
	// configuration.  One entry in this table reflects a
	// profile defined by a manager which can be used to
	// configure the modem for a physical line
	AdslLineAlarmConfProfileTableOid = "1.3.6.1.2.1.10.94.1.1.15"
	AdslLCSMibOid                    = "1.3.6.1.2.1.10.94.1.1.16"
	AdslTrapsOid                     = "1.3.6.1.2.1.10.94.1.2"
	AdslAtucTrapsOid                 = "1.3.6.1.2.1.10.94.1.2.1"
	AdslAturTrapsOid                 = "1.3.6.1.2.1.10.94.1.2.2"
	AdslConformanceOid               = "1.3.6.1.2.1.10.94.1.3"
	AdslGroupsOid                    = "1.3.6.1.2.1.10.94.1.3.1"
	AdslCompliancesOid               = "1.3.6.1.2.1.10.94.1.3.2"
)

// Table: adslAtucChanIntervalTable (1.3.6.1.2.1.10.94.1.1.12)
// This table provides one row for each ATUC channel's
// performance data collection interval.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAtucChanIntervalTable struct {
	Entries map[string]AdslAtucChanIntervalEntry `snmp:"1.3.6.1.2.1.10.94.1.1.12.1"`
}

// Entry: adslAtucChanIntervalEntry (1.3.6.1.2.1.10.94.1.1.12.1)
// An entry in the adslAtucIntervalTable.
type AdslAtucChanIntervalEntry struct {
	// Count of all blocks received with errors that were
	// corrected on this channel during this interval.
	AdslAtucChanIntervalCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.4"`
	// Performance Data Interval number 1 is the
	// the most recent previous interval; interval
	// 96 is 24 hours ago.  Intervals 2..96 are
	// optional.
	AdslAtucChanIntervalNumber uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.1"`
	// Count of all encoded blocks received on this channel
	// during this interval.
	AdslAtucChanIntervalReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.2"`
	// Count of all encoded blocks transmitted on this
	// channel during this interval.
	AdslAtucChanIntervalTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.3"`
	// Count of all blocks received with uncorrectable
	// errors on this channel during this interval.
	AdslAtucChanIntervalUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.5"`
	// This variable indicates if the data for this
	// interval is valid.
	AdslAtucChanIntervalValidData uint `snmp:"1.3.6.1.2.1.10.94.1.1.12.1.6" snmpType:"enum" snmpEnum:"TruthValueMap"`
}

// Table: adslAtucChanPerfDataTable (1.3.6.1.2.1.10.94.1.1.10)
// This table provides one row for each ATUC channel.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAtucChanPerfDataTable struct {
	Entries map[string]AdslAtucChanPerfDataEntry `snmp:"1.3.6.1.2.1.10.94.1.1.10.1"`
}

// Entry: adslAtucChanPerfDataEntry (1.3.6.1.2.1.10.94.1.1.10.1)
// An entry in adslAtucChanPerfDataTable.
type AdslAtucChanPerfDataEntry struct {
	// Count of all blocks received with errors that were
	// corrected since agent reset.  These blocks are passed
	// on as good data.
	AdslAtucChanCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.3"`
	// Count of all blocks received with errors that were
	// corrected on this channel within the current 15 minute
	// interval.
	AdslAtucChanPerfCurr15MinCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.10"`
	// Count of all encoded blocks received on this channel
	// within the current 15 minute interval.
	AdslAtucChanPerfCurr15MinReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.8"`
	// Total elapsed seconds in this interval.
	AdslAtucChanPerfCurr15MinTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.7"`
	// Count of all encoded blocks transmitted on this
	// channel within the current 15 minute interval.
	AdslAtucChanPerfCurr15MinTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.9"`
	// Count of all blocks received with uncorrectable
	// errors on this channel within the current 15 minute
	// interval.
	AdslAtucChanPerfCurr15MinUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.11"`
	// Count of all blocks received with errors that were
	// corrected on this channel during the current day as
	// measured by adslAtucChanPerfCurr1DayTimeElapsed.
	AdslAtucChanPerfCurr1DayCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.15"`
	// Count of all encoded blocks received on this
	// channel during the current day as measured by
	// adslAtucChanPerfCurr1DayTimeElapsed.
	AdslAtucChanPerfCurr1DayReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.13"`
	// Number of seconds that have elapsed since the
	// beginning of the current 1-day interval.
	AdslAtucChanPerfCurr1DayTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.12"`
	// Count of all encoded blocks transmitted on this
	// channel during the current day as measured by
	// adslAtucChanPerfCurr1DayTimeElapsed.
	AdslAtucChanPerfCurr1DayTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.14"`
	// Count of all blocks received with uncorrectable
	// errors on this channel during the current day as
	// measured by adslAtucChanPerfCurr1DayTimeElapsed.
	AdslAtucChanPerfCurr1DayUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.16"`
	// The number of intervals in the range from
	// 0 to the value of adslAtucChanPerfValidIntervals
	// for which no data is available. This object
	// will typically be zero except in cases where
	// the data for some intervals are not available
	// (e.g., in proxy situations).
	AdslAtucChanPerfInvalidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.6"`
	// Count of all blocks received with errors that were
	// corrected on this channel within the most recent
	// previous 1-day period.
	AdslAtucChanPerfPrev1DayCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.20"`
	// The amount of time in the previous 1-day interval
	// over which the performance monitoring information
	// is actually counted. This value will be the same as
	// the interval duration except in a situation where
	// performance monitoring data could not be collected
	// for any reason.
	AdslAtucChanPerfPrev1DayMoniSecs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.17"`
	// Count of all encoded blocks received on this
	// channel within the most recent previous 1-day
	// period.
	AdslAtucChanPerfPrev1DayReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.18"`
	// Count of all encoded blocks transmitted on this
	// channel within the most recent previous 1-day
	// period.
	AdslAtucChanPerfPrev1DayTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.19"`
	// Count of all blocks received with uncorrectable
	// errors on this channel within the most recent previous
	// 1-day period.
	AdslAtucChanPerfPrev1DayUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.21"`
	// The number of previous 15-minute intervals in the
	// interval table for which data was collected.  Given
	// that <n> is the maximum # of intervals supported.
	// The value will be <n> unless the measurement was
	// (re-)started within the last (<n>*15) minutes, in which
	// case the value will be the number of complete 15
	// minute intervals for which the agent has at least
	// some data. In certain cases (e.g., in the case
	// where the agent is a proxy) it is possible that some
	// intervals are unavailable.  In this case, this
	// interval is the maximum interval number for
	// which data is available.
	AdslAtucChanPerfValidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.5"`
	// Count of all encoded blocks received on this channel
	// since agent reset.
	AdslAtucChanReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.1"`
	// Count of all encoded blocks transmitted on this
	// channel since agent reset.
	AdslAtucChanTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.2"`
	// Count of all blocks received with uncorrectable
	// errors since agent reset.
	AdslAtucChanUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.10.1.4"`
}

// Table: adslAtucChanTable (1.3.6.1.2.1.10.94.1.1.4)
// This table provides one row for each ATUC channel.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAtucChanTable struct {
	Entries map[string]AdslAtucChanEntry `snmp:"1.3.6.1.2.1.10.94.1.1.4.1"`
}

// Entry: adslAtucChanEntry (1.3.6.1.2.1.10.94.1.1.4.1)
// An entry in the adslAtucChanTable.
type AdslAtucChanEntry struct {
	// Indicates the length of the channel data-block
	// on which the CRC operates.  Refer to Line Code
	// Specific MIBs, [11] and [12] for more
	// information.
	AdslAtucChanCrcBlockLength uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.4.1.4"`
	// Actual transmit rate on this channel.
	AdslAtucChanCurrTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.4.1.2"`
	// Interleave Delay for this channel.
	// Interleave delay applies only to the
	// interleave channel and defines the mapping
	// (relative spacing) between subsequent input
	// bytes at the interleaver input and their placement
	// in the bit stream at the interleaver output.
	// Larger numbers provide greater separation between
	// consecutive input bytes in the output bit stream
	// allowing for improved impulse noise immunity at
	// the expense of payload latency.
	// In the case where the ifType is Fast(125), use
	// noSuchObject.
	AdslAtucChanInterleaveDelay uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.4.1.1"`
	// The rate at the time of the last
	// adslAtucRateChangeTrap event. It is also set at
	// initialization to prevent a trap being sent.
	// Rate changes less than adslAtucThresh(*)RateDown
	// or less than adslAtucThresh(*)RateUp will not
	// cause a trap or cause this object to change.
	// (*) == Fast or Interleave.
	// See AdslLineAlarmConfProfileEntry.
	AdslAtucChanPrevTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.4.1.3"`
}

// Table: adslAtucIntervalTable (1.3.6.1.2.1.10.94.1.1.8)
// This table provides one row for each ATUC
// performance data collection interval.
// ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslAtucIntervalTable struct {
	Entries map[string]AdslAtucIntervalEntry `snmp:"1.3.6.1.2.1.10.94.1.1.8.1"`
}

// Entry: adslAtucIntervalEntry (1.3.6.1.2.1.10.94.1.1.8.1)
// An entry in the adslAtucIntervalTable.
type AdslAtucIntervalEntry struct {
	// Count of Errored Seconds in the interval.
	// The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAtucIntervalESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.6"`
	// Count of the line initialization attempts
	// during the interval. Includes both successful
	// and failed attempts.
	AdslAtucIntervalInits uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.7"`
	// Count of seconds in the interval when there was Loss
	// of Framing.
	AdslAtucIntervalLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.2"`
	// Count of seconds in the interval when there was Loss
	// of Link.
	AdslAtucIntervalLols uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.4"`
	// Count of seconds in the interval when there was Loss
	// of Signal.
	AdslAtucIntervalLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.3"`
	// Count of seconds in the interval when there was Loss
	// of Power.
	AdslAtucIntervalLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.5"`
	// Performance Data Interval number 1 is the
	// the most recent previous interval; interval
	// 96 is 24 hours ago.  Intervals 2..96 are
	// optional.
	AdslAtucIntervalNumber uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.1"`
	// This variable indicates if the data for this
	// interval is valid.
	AdslAtucIntervalValidData uint `snmp:"1.3.6.1.2.1.10.94.1.1.8.1.8" snmpType:"enum" snmpEnum:"TruthValueMap"`
}

// Table: adslAtucPerfDataTable (1.3.6.1.2.1.10.94.1.1.6)
// This table provides one row for each ATUC.
// ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslAtucPerfDataTable struct {
	Entries map[string]AdslAtucPerfDataEntry `snmp:"1.3.6.1.2.1.10.94.1.1.6.1"`
}

// Entry: adslAtucPerfDataEntry (1.3.6.1.2.1.10.94.1.1.6.1)
// An entry in adslAtucPerfDataTable.
type AdslAtucPerfDataEntry struct {
	// Count of Errored Seconds in the current 15 minute
	// interval.  The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAtucPerfCurr15MinESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.14"`
	// Count of the line initialization attempts in the
	// current 15 minute interval. Includes both successful
	// and failed attempts.
	AdslAtucPerfCurr15MinInits uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.15"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Framing.
	AdslAtucPerfCurr15MinLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.10"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Link.
	AdslAtucPerfCurr15MinLols uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.12"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Signal.
	AdslAtucPerfCurr15MinLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.11"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Power.
	AdslAtucPerfCurr15MinLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.13"`
	// Total elapsed seconds in this interval.
	AdslAtucPerfCurr15MinTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.9"`
	// Count of Errored Seconds during the current day as
	// measured by adslAtucPerfCurr1DayTimeElapsed.
	// The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAtucPerfCurr1DayESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.21"`
	// Count of the line initialization attempts in the
	// day as measured by adslAtucPerfCurr1DayTimeElapsed.
	// Includes both successful and failed attempts.
	AdslAtucPerfCurr1DayInits uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.22"`
	// Count of the number of seconds when there was Loss of
	// Framing during the current day as measured by
	// adslAtucPerfCurr1DayTimeElapsed.
	AdslAtucPerfCurr1DayLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.17"`
	// Count of the number of seconds when there was Loss of
	// Link during the current day as measured by
	// adslAtucPerfCurr1DayTimeElapsed.
	AdslAtucPerfCurr1DayLols uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.19"`
	// Count of the number of seconds when there was Loss of
	// Signal during the current day as measured by
	// adslAtucPerfCurr1DayTimeElapsed.
	AdslAtucPerfCurr1DayLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.18"`
	// Count of the number of seconds when there was Loss of
	// Power during the current day as measured by
	// adslAtucPerfCurr1DayTimeElapsed.
	AdslAtucPerfCurr1DayLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.20"`
	// Number of seconds that have elapsed since the
	// beginning of the current 1-day interval.
	AdslAtucPerfCurr1DayTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.16"`
	// Count of the number of Errored Seconds since agent
	// reset.  The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAtucPerfESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.5"`
	// Count of the line initialization attempts since
	// agent reset. Includes both successful and failed
	// attempts.
	AdslAtucPerfInits uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.6"`
	// The number of intervals in the range from
	// 0 to the value of adslAtucPerfValidIntervals
	// for which no data is available. This object
	// will typically be zero except in cases where
	// the data for some intervals are not available
	// (e.g., in proxy situations).
	AdslAtucPerfInvalidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.8"`
	// Count of the number of Loss of Framing failures since
	// agent reset.
	AdslAtucPerfLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.1"`
	// Count of the number of Loss of Link failures since
	// agent reset.
	AdslAtucPerfLols uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.3"`
	// Count of the number of Loss of Signal failures since
	// agent reset.
	AdslAtucPerfLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.2"`
	// Count of the number of Loss of Power failures since
	// agent reset.
	AdslAtucPerfLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.4"`
	// Count of Errored Seconds within the most recent
	// previous 1-day period. The errored second parameter is
	// a count of one-second intervals containing one or more
	// crc anomalies, or one or more los or sef defects.
	AdslAtucPerfPrev1DayESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.28"`
	// Count of the line initialization attempts in the most
	// recent previous 1-day period. Includes both successful
	// and failed attempts.
	AdslAtucPerfPrev1DayInits uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.29"`
	// Count of seconds in the interval when there was
	// Loss of Framing within the most recent previous
	// 1-day period.
	AdslAtucPerfPrev1DayLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.24"`
	// Count of seconds in the interval when there was
	// Loss of Link within the most recent previous
	// 1-day period.
	AdslAtucPerfPrev1DayLols uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.26"`
	// Count of seconds in the interval when there was
	// Loss of Signal within the most recent previous
	// 1-day period.
	AdslAtucPerfPrev1DayLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.25"`
	// Count of seconds in the interval when there was
	// Loss of Power within the most recent previous
	// 1-day period.
	AdslAtucPerfPrev1DayLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.27"`
	// The amount of time in the previous 1-day interval
	// over which the performance monitoring information
	// is actually counted. This value will be the same as
	// the interval duration except in a situation where
	// performance monitoring data could not be collected
	// for any reason.
	AdslAtucPerfPrev1DayMoniSecs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.23"`
	// The number of previous 15-minute intervals in the
	// interval table for which data was collected.  Given
	// that <n> is the maximum # of intervals supported.
	// The value will be <n> unless the measurement was
	// (re-)started within the last (<n>*15) minutes, in which
	// case the value will be the number of complete 15
	// minute intervals for which the agent has at least
	// some data. In certain cases (e.g., in the case
	// where the agent is a proxy) it is possible that some
	// intervals are unavailable.  In this case, this
	// interval is the maximum interval number for
	// which data is available.
	AdslAtucPerfValidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.6.1.7"`
}

// Table: adslAtucPhysTable (1.3.6.1.2.1.10.94.1.1.2)
// This table provides one row for each ATUC.
// Each row contains the Physical Layer Parameters
// table for that ATUC. ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslAtucPhysTable struct {
	Entries map[string]AdslAtucPhysEntry `snmp:"1.3.6.1.2.1.10.94.1.1.2.1"`
}

// Entry: adslAtucPhysEntry (1.3.6.1.2.1.10.94.1.1.2.1)
// An entry in the adslAtucPhysTable.
type AdslAtucPhysEntry struct {
	// Measured difference in the total power transmitted by
	// the peer ATU and the total power received by this ATU.
	AdslAtucCurrAtn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.5"`
	// Indicates the maximum currently attainable data rate
	// by the ATU.  This value will be equal or greater than
	// the current line rate.
	AdslAtucCurrAttainableRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.8"`
	// Measured total output power transmitted by this ATU.
	// This is the measurement that was reported during
	// the last activation sequence.
	AdslAtucCurrOutputPwr int64 `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.7"`
	// Noise Margin as seen by this ATU with respect to its
	// received signal in tenth dB.
	AdslAtucCurrSnrMgn int64 `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.4"`
	// Indicates current state of the ATUC line.  This is a
	// bit-map of possible conditions.  The various bit
	// positions are:
	// 0      noDefect             There no defects on the line
	// 1      lossOfFraming        ATUC failure due to not
	// receiving valid frame.
	// 2      lossOfSignal         ATUC failure due to not
	// receiving signal.
	// 3      lossOfPower          ATUC failure due to loss of
	// power.
	// Note: the Agent may still
	// function.
	// 4      lossOfSignalQuality  Loss of Signal Quality is
	// declared when the Noise Margin
	// falls below the Minimum Noise
	// Margin, or the bit-error-rate
	// exceeds 10^-7.
	// 5      lossOfLink           ATUC failure due to inability
	// to link with ATUR.
	// 6      dataInitFailure      ATUC failure during
	// initialization due to bit
	// errors corrupting startup
	// exchange data.
	// 7      configInitFailure    ATUC failure during
	// initialization due to peer
	// ATU not able to support
	// requested configuration
	// 8      protocolInitFailure  ATUC failure during
	// initialization due to
	// incompatible protocol used by
	// the peer ATU.
	// 9      noPeerAtuPresent     ATUC failure during
	// initialization due to no
	// activation sequence detected
	// from peer ATU.
	// This is intended to supplement ifOperStatus.
	AdslAtucCurrStatus uint `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.6"`
	// The vendor specific string that identifies the
	// vendor equipment.
	AdslAtucInvSerialNumber string `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.1" snmpType:"octet-string"`
	// The vendor ID code is a copy of the binary
	// vendor identification field defined by the
	// PHY[10] and expressed as readable characters.
	AdslAtucInvVendorID string `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.2" snmpType:"octet-string"`
	// The vendor specific version number sent by this ATU
	// as part of the initialization messages.  It is a copy
	// of the binary version number field defined by the
	// PHY[10] and expressed as readable characters.
	AdslAtucInvVersionNumber string `snmp:"1.3.6.1.2.1.10.94.1.1.2.1.3" snmpType:"octet-string"`
}

// Table: adslAturChanIntervalTable (1.3.6.1.2.1.10.94.1.1.13)
// This table provides one row for each ATUR channel's
// performance data collection interval.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAturChanIntervalTable struct {
	Entries map[string]AdslAturChanIntervalEntry `snmp:"1.3.6.1.2.1.10.94.1.1.13.1"`
}

// Entry: adslAturChanIntervalEntry (1.3.6.1.2.1.10.94.1.1.13.1)
// An entry in the adslAturIntervalTable.
type AdslAturChanIntervalEntry struct {
	// Count of all blocks received with errors that were
	// corrected on this channel during this interval.
	AdslAturChanIntervalCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.4"`
	// Performance Data Interval number 1 is the
	// the most recent previous interval; interval
	// 96 is 24 hours ago.  Intervals 2..96 are
	// optional.
	AdslAturChanIntervalNumber uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.1"`
	// Count of all encoded blocks received on this channel
	// during this interval.
	AdslAturChanIntervalReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.2"`
	// Count of all encoded blocks transmitted on this
	// channel during this interval.
	AdslAturChanIntervalTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.3"`
	// Count of all blocks received with uncorrectable
	// errors on this channel during this interval.
	AdslAturChanIntervalUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.5"`
	// This variable indicates if the data for this
	// interval is valid.
	AdslAturChanIntervalValidData uint `snmp:"1.3.6.1.2.1.10.94.1.1.13.1.6" snmpType:"enum" snmpEnum:"TruthValueMap"`
}

// Table: adslAturChanPerfDataTable (1.3.6.1.2.1.10.94.1.1.11)
// This table provides one row for each ATUR channel.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAturChanPerfDataTable struct {
	Entries map[string]AdslAturChanPerfDataEntry `snmp:"1.3.6.1.2.1.10.94.1.1.11.1"`
}

// Entry: adslAturChanPerfDataEntry (1.3.6.1.2.1.10.94.1.1.11.1)
// An entry in adslAturChanPerfDataTable.
type AdslAturChanPerfDataEntry struct {
	// Count of all blocks received with errors that were
	// corrected since agent reset.  These blocks are passed
	// on as good data.
	AdslAturChanCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.3"`
	// Count of all blocks received with errors that were
	// corrected on this channel within the current 15 minute
	// interval.
	AdslAturChanPerfCurr15MinCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.10"`
	// Count of all encoded blocks received on this
	// channel within the current 15 minute interval.
	AdslAturChanPerfCurr15MinReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.8"`
	// Total elapsed seconds in this interval.
	// A full interval is 900 seconds.
	AdslAturChanPerfCurr15MinTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.7"`
	// Count of all encoded blocks transmitted on this
	// channel within the current 15 minute interval.
	AdslAturChanPerfCurr15MinTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.9"`
	// Count of all blocks received with uncorrectable
	// errors on this channel within the current 15 minute
	// interval.
	AdslAturChanPerfCurr15MinUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.11"`
	// Count of all blocks received with errors that were
	// corrected on this channel during the current day as
	// measured by adslAturChanPerfCurr1DayTimeElapsed.
	AdslAturChanPerfCurr1DayCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.15"`
	// Count of all encoded blocks received on this
	// channel during the current day as measured by
	// adslAturChanPerfCurr1DayTimeElapsed.
	AdslAturChanPerfCurr1DayReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.13"`
	// Number of seconds that have elapsed since the
	// beginning of the current 1-day interval.
	AdslAturChanPerfCurr1DayTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.12"`
	// Count of all encoded blocks transmitted on this
	// channel during the current day as measured by
	// adslAturChanPerfCurr1DayTimeElapsed.
	AdslAturChanPerfCurr1DayTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.14"`
	// Count of all blocks received with uncorrectable
	// errors on this channel during the current day as
	// measured by adslAturChanPerfCurr1DayTimeElapsed.
	AdslAturChanPerfCurr1DayUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.16"`
	// The number of intervals in the range from
	// 0 to the value of adslAturChanPerfValidIntervals
	// for which no data is available. This object
	// will typically be zero except in cases where
	// the data for some intervals are not available
	// (e.g., in proxy situations).
	AdslAturChanPerfInvalidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.6"`
	// Count of all blocks received with errors that were
	// corrected on this channel within the most recent
	// previous 1-day period.
	AdslAturChanPerfPrev1DayCorrectedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.20"`
	// The amount of time in the previous 1-day interval
	// over which the performance monitoring information
	// is actually counted. This value will be the same as
	// the interval duration except in a situation where
	// performance monitoring data could not be collected
	// for any reason.
	AdslAturChanPerfPrev1DayMoniSecs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.17"`
	// Count of all encoded blocks received on this
	// channel within the most recent previous 1-day
	// period.
	AdslAturChanPerfPrev1DayReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.18"`
	// Count of all encoded blocks transmitted on this
	// channel within the most recent previous 1-day
	// period.
	AdslAturChanPerfPrev1DayTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.19"`
	// Count of all blocks received with uncorrectable
	// errors on this channel within the most recent previous
	// 1-day period.
	AdslAturChanPerfPrev1DayUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.21"`
	// The number of previous 15-minute intervals in the
	// interval table for which data was collected.  Given
	// that <n> is the maximum # of intervals supported.
	// The value will be <n> unless the measurement was
	// (re-)started within the last (<n>*15) minutes, in which
	// case the value will be the number of complete 15
	// minute intervals for which the agent has at least
	// some data. In certain cases (e.g., in the case
	// where the agent is a proxy) it is possible that some
	// intervals are unavailable.  In this case, this
	// interval is the maximum interval number for
	// which data is available.
	AdslAturChanPerfValidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.5"`
	// Count of all encoded blocks received on this channel
	// since agent reset.
	AdslAturChanReceivedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.1"`
	// Count of all encoded blocks transmitted on this
	// channel since agent reset.
	AdslAturChanTransmittedBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.2"`
	// Count of all blocks received with uncorrectable
	// errors since agent reset.
	AdslAturChanUncorrectBlks uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.11.1.4"`
}

// Table: adslAturChanTable (1.3.6.1.2.1.10.94.1.1.5)
// This table provides one row for each ATUR channel.
// ADSL channel interfaces are those ifEntries
// where ifType is equal to adslInterleave(124)
// or adslFast(125).
type AdslAturChanTable struct {
	Entries map[string]AdslAturChanEntry `snmp:"1.3.6.1.2.1.10.94.1.1.5.1"`
}

// Entry: adslAturChanEntry (1.3.6.1.2.1.10.94.1.1.5.1)
// An entry in the adslAturChanTable.
type AdslAturChanEntry struct {
	// Indicates the length of the channel data-block
	// on which the CRC operates.  Refer to Line Code
	// Specific MIBs, [11] and [12] for more
	// information.
	AdslAturChanCrcBlockLength uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.5.1.4"`
	// Actual transmit rate on this channel.
	AdslAturChanCurrTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.5.1.2"`
	// Interleave Delay for this channel.
	// Interleave delay applies only to the
	// interleave channel and defines the mapping
	// (relative spacing) between subsequent input
	// bytes at the interleaver input and their placement
	// in the bit stream at the interleaver output.
	// Larger numbers provide greater separation between
	// consecutive input bytes in the output bit stream
	// allowing for improved impulse noise immunity at
	// the expense of payload latency.
	// In the case where the ifType is Fast(125), use
	// noSuchObject.
	AdslAturChanInterleaveDelay uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.5.1.1"`
	// The rate at the time of the last
	// adslAturRateChangeTrap event. It is also set at
	// initialization to prevent a trap being sent.
	// Rate changes less than adslAturThresh(*)RateDown
	// or less than adslAturThresh(*)RateUp will not
	// cause a trap or cause this object to change.
	// (*) == Fast or Interleave.
	// See AdslLineAlarmConfProfileEntry.
	AdslAturChanPrevTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.5.1.3"`
}

// Table: adslAturIntervalTable (1.3.6.1.2.1.10.94.1.1.9)
// This table provides one row for each ATUR
// performance data collection interval.
// ADSL physical interfaces are those
// ifEntries where ifType is equal to adsl(94).
type AdslAturIntervalTable struct {
	Entries map[string]AdslAturIntervalEntry `snmp:"1.3.6.1.2.1.10.94.1.1.9.1"`
}

// Entry: adslAturIntervalEntry (1.3.6.1.2.1.10.94.1.1.9.1)
// An entry in the adslAturIntervalTable.
type AdslAturIntervalEntry struct {
	// Count of Errored Seconds in the interval.
	// The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAturIntervalESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.5"`
	// Count of seconds in the interval when there was
	// Loss of Framing.
	AdslAturIntervalLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.2"`
	// Count of seconds in the interval when there was
	// Loss of Signal.
	AdslAturIntervalLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.3"`
	// Count of seconds in the interval when there was
	// Loss of Power.
	AdslAturIntervalLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.4"`
	// Performance Data Interval number 1 is the
	// the most recent previous interval; interval
	// 96 is 24 hours ago.  Intervals 2..96 are
	// optional.
	AdslAturIntervalNumber uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.1"`
	// This variable indicates if the data for this
	// interval is valid.
	AdslAturIntervalValidData uint `snmp:"1.3.6.1.2.1.10.94.1.1.9.1.6" snmpType:"enum" snmpEnum:"TruthValueMap"`
}

// Table: adslAturPerfDataTable (1.3.6.1.2.1.10.94.1.1.7)
// This table provides one row for each ATUR.
// ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslAturPerfDataTable struct {
	Entries map[string]AdslAturPerfDataEntry `snmp:"1.3.6.1.2.1.10.94.1.1.7.1"`
}

// Entry: adslAturPerfDataEntry (1.3.6.1.2.1.10.94.1.1.7.1)
// An entry in adslAturPerfDataTable.
type AdslAturPerfDataEntry struct {
	// Count of Errored Seconds in the current 15 minute
	// interval.  The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAturPerfCurr15MinESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.11"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Framing.
	AdslAturPerfCurr15MinLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.8"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Signal.
	AdslAturPerfCurr15MinLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.9"`
	// Count of seconds in the current 15 minute interval
	// when there was Loss of Power.
	AdslAturPerfCurr15MinLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.10"`
	// Total elapsed seconds in this interval.
	AdslAturPerfCurr15MinTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.7"`
	// Count of Errored Seconds during the current day as
	// measured by adslAturPerfCurr1DayTimeElapsed.
	// The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAturPerfCurr1DayESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.16"`
	// Count of the number of seconds when there was Loss
	// of Framing during the current day as measured by
	// adslAturPerfCurr1DayTimeElapsed.
	AdslAturPerfCurr1DayLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.13"`
	// Count of the number of seconds when there was Loss
	// of Signal during the current day as measured by
	// adslAturPerfCurr1DayTimeElapsed.
	AdslAturPerfCurr1DayLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.14"`
	// Count of the number of seconds when there was Loss
	// of Power during the current day as measured by
	// adslAturPerfCurr1DayTimeElapsed.
	AdslAturPerfCurr1DayLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.15"`
	// Number of seconds that have elapsed since the
	// beginning of the current 1-day interval.
	AdslAturPerfCurr1DayTimeElapsed uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.12"`
	// Count of the number of Errored Seconds since agent
	// reset.  The errored second parameter is a count of
	// one-second intervals containing one or more crc
	// anomalies, or one or more los or sef defects.
	AdslAturPerfESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.4"`
	// The number of intervals in the range from
	// 0 to the value of adslAturPerfValidIntervals
	// for which no data is available. This object
	// will typically be zero except in cases where
	// the data for some intervals are not available
	// (e.g., in proxy situations).
	AdslAturPerfInvalidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.6"`
	// Count of the number of Loss of Framing failures since
	// agent reset.
	AdslAturPerfLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.1"`
	// Count of the number of Loss of Signal failures since
	// agent reset.
	AdslAturPerfLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.2"`
	// Count of the number of Loss of Power failures since
	// agent reset.
	AdslAturPerfLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.3"`
	// Count of Errored Seconds within the most recent
	// previous 1-day period. The errored second parameter is
	// a count of one-second intervals containing one or more
	// crc anomalies, or one or more los or sef defects.
	AdslAturPerfPrev1DayESs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.21"`
	// Count of seconds in the interval when there was
	// Loss of Framing within the most recent previous
	// 1-day period.
	AdslAturPerfPrev1DayLofs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.18"`
	// Count of seconds in the interval when there was
	// Loss of Signal within the most recent previous
	// 1-day period.
	AdslAturPerfPrev1DayLoss uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.19"`
	// Count of seconds in the interval when there was
	// Loss of Power within the most recent previous
	// 1-day period.
	AdslAturPerfPrev1DayLprs uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.20"`
	// The amount of time in the previous 1-day interval
	// over which the performance monitoring information
	// is actually counted. This value will be the same as
	// the interval duration except in a situation where
	// performance monitoring data could not be collected
	// for any reason.
	AdslAturPerfPrev1DayMoniSecs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.17"`
	// The number of previous 15-minute intervals in the
	// interval table for which data was collected.  Given
	// that <n> is the maximum # of intervals supported.
	// The value will be <n> unless the measurement was
	// (re-)started within the last (<n>*15) minutes, in which
	// case the value will be the number of complete 15
	// minute intervals for which the agent has at least
	// some data. In certain cases (e.g., in the case
	// where the agent is a proxy) it is possible that some
	// intervals are unavailable.  In this case, this
	// interval is the maximum interval number for
	// which data is available.
	AdslAturPerfValidIntervals uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.7.1.5"`
}

// Table: adslAturPhysTable (1.3.6.1.2.1.10.94.1.1.3)
// This table provides one row for each ATUR
// Each row contains the Physical Layer Parameters
// table for that ATUR. ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslAturPhysTable struct {
	Entries map[string]AdslAturPhysEntry `snmp:"1.3.6.1.2.1.10.94.1.1.3.1"`
}

// Entry: adslAturPhysEntry (1.3.6.1.2.1.10.94.1.1.3.1)
// An entry in the adslAturPhysTable.
type AdslAturPhysEntry struct {
	// Measured difference in the total power transmitted by
	// the peer ATU and the total power received by this ATU.
	AdslAturCurrAtn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.5"`
	// Indicates the maximum currently attainable data rate
	// by the ATU.  This value will be equal or greater than
	// the current line rate.
	AdslAturCurrAttainableRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.8"`
	// Measured total output power transmitted by this ATU.
	// This is the measurement that was reported during
	// the last activation sequence.
	AdslAturCurrOutputPwr int64 `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.7"`
	// Noise Margin as seen by this ATU with respect to its
	// received signal in tenth dB.
	AdslAturCurrSnrMgn int64 `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.4"`
	// Indicates current state of the ATUR line.  This is a
	// bit-map of possible conditions.  Due to the isolation
	// of the ATUR when line problems occur, many state
	// conditions like loss of power, loss of quality signal,
	// and initialization errors,  can not be determined.
	// While trouble shooting ATUR, also use object,
	// adslAtucCurrStatus.  The various bit positions are:
	// 0      noDefect             There no defects on the line
	// 1      lossOfFraming        ATUR failure due to not
	// receiving valid frame
	// 2      lossOfSignal         ATUR failure due to not
	// receiving signal
	// 3      lossOfPower          ATUR failure due to loss of
	// power
	// 4      lossOfSignalQuality  Loss of Signal Quality is
	// declared when the Noise Margin
	// falls below the Minimum Noise
	// Margin, or the
	// bit-error-rate exceeds 10^-7.
	// This is intended to supplement ifOperStatus.
	AdslAturCurrStatus uint `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.6"`
	// The vendor specific string that identifies the
	// vendor equipment.
	AdslAturInvSerialNumber string `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.1" snmpType:"octet-string"`
	// The vendor ID code is a copy of the binary
	// vendor identification field defined by the
	// PHY[10] and expressed as readable characters.
	AdslAturInvVendorID string `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.2" snmpType:"octet-string"`
	// The vendor specific version number sent by this ATU
	// as part of the initialization messages.  It is a copy
	// of the binary version number field defined by the
	// PHY[10] and expressed as readable characters.
	AdslAturInvVersionNumber string `snmp:"1.3.6.1.2.1.10.94.1.1.3.1.3" snmpType:"octet-string"`
}

// Table: adslLineAlarmConfProfileTable (1.3.6.1.2.1.10.94.1.1.15)
// This table contains information on the ADSL line
// configuration.  One entry in this table reflects a
// profile defined by a manager which can be used to
// configure the modem for a physical line
type AdslLineAlarmConfProfileTable struct {
	Entries map[string]AdslLineAlarmConfProfileEntry `snmp:"1.3.6.1.2.1.10.94.1.1.15.1"`
}

// Entry: adslLineAlarmConfProfileEntry (1.3.6.1.2.1.10.94.1.1.15.1)
// Each entry consists of a list of parameters that
// represents the configuration of an ADSL modem.
// When `dynamic' profiles are implemented, a default
// profile will always exist.  This profile's name will
// be set to `DEFVAL' and its parameters will be set to
// vendor specific values, unless otherwise specified
// in this document.
// When `static' profiles are implemented, profiles
// are automaticly created or destroyed as ADSL
// physical lines are discovered and removed by
// the system.  The name of the profile will be
// equivalent to the decimal value of the line's
// interface index.
type AdslLineAlarmConfProfileEntry struct {
	// Enables and disables the InitFailureTrap.  This
	// object is defaulted disable(2).
	AdslAtucInitFailureTrapEnable uint `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.11" snmpType:"enum" snmpEnum:"EnumerationMap"`
	// The number of Errored Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAtucPerfESsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAtucThresh15MinESs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.6"`
	// The number of Loss of Frame Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAtucPerfLofsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAtucThresh15MinLofs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.2"`
	// The number of Loss of Link Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAtucPerfLolsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAtucThresh15MinLols uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.4"`
	// The number of Loss of Signal Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAtucPerfLossThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAtucThresh15MinLoss uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.3"`
	// The number of Loss of Power Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAtucPerfLprsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAtucThresh15MinLprs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.5"`
	// Applies to `Fast' channels only.
	// Configured change in rate causing an
	// adslAtucRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate <= ChanPrevTxRate minus the value of
	// this object. A value of `0' will disable the trap.
	AdslAtucThreshFastRateDown uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.9"`
	// Applies to `Fast' channels only.
	// Configured change in rate causing an
	// adslAtucRateChangeTrap. A trap is produced when:
	// ChanCurrTxRate >= ChanPrevTxRate plus the value of
	// this object. A value of `0' will disable the trap.
	AdslAtucThreshFastRateUp uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.7"`
	// Applies to `Interleave' channels only.
	// Configured change in rate causing an
	// adslAtucRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate <= ChanPrevTxRate minus the value of
	// this object. A value of `0' will disable the trap.
	AdslAtucThreshInterleaveRateDown uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.10"`
	// Applies to `Interleave' channels only.
	// Configured change in rate causing an
	// adslAtucRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate >= ChanPrevTxRate plus the value of
	// this object. A value of `0' will disable the trap.
	AdslAtucThreshInterleaveRateUp uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.8"`
	// The number of Errored Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAturPerfESsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAturThresh15MinESs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.15"`
	// The number of Loss of Frame Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAturPerfLofsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAturThresh15MinLofs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.12"`
	// The number of Loss of Signal Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAturPerfLossThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAturThresh15MinLoss uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.13"`
	// The number of Loss of Power Seconds
	// encountered by an ADSL interface within any given 15
	// minutes performance data collection period, which
	// causes the SNMP agent to send an
	// adslAturPerfLprsThreshTrap.
	// One trap will be sent per interval per interface.
	// A value of `0' will disable the trap.
	AdslAturThresh15MinLprs uint64 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.14"`
	// Applies to `Fast' channels only.
	// Configured change in rate causing an
	// adslAturRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate <= ChanPrevTxRate minus the value of
	// this object. A value of `0' will disable the trap.
	AdslAturThreshFastRateDown uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.18"`
	// Applies to `Fast' channels only.
	// Configured change in rate causing an
	// adslAturRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate >= ChanPrevTxRate plus the value of
	// this object. A value of `0' will disable the trap.
	AdslAturThreshFastRateUp uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.16"`
	// Applies to `Interleave' channels only.
	// Configured change in rate causing an
	// adslAturRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate <= ChanPrevTxRate minus the value of
	// this object. A value of `0' will disable the trap.
	AdslAturThreshInterleaveRateDown uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.19"`
	// Applies to `Interleave' channels only.
	// configured change in rate causing an
	// adslAturRateChangeTrap.  A trap is produced when:
	// ChanCurrTxRate >= ChanPrevTxRate plus the value of
	// this object. A value of `0' will disable the trap.
	AdslAturThreshInterleaveRateUp uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.17"`
	// This object is used by the line alarm configuration
	// table in order to identify a row of this table.
	// When `dynamic' profiles are implemented, the profile
	// name is user specified.  Also, the system will always
	// provide a default profile whose name is `DEFVAL'.
	// When `static' profiles are implemented, there is an
	// one-to-one relationship between each line and its
	// profile.  In which case, the profile name will
	// need to algorithmicly represent the Line's ifIndex.
	// Therefore, the profile's name is a decimalized string
	// of the ifIndex that is fixed-length (i.e., 10) with
	// leading zero(s).  For example, the profile name for
	// ifIndex which equals '15' will be '0000000015'.
	AdslLineAlarmConfProfileName string `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.1" snmpType:"octet-string"`
	// This object is used to create a new row or modify or
	// delete an existing row in this table.
	// A profile activated by setting this object to
	// `active'.  When `active' is set, the system
	// will validate the profile.
	// Before a profile can be deleted or taken out of
	// service, (by setting this object to `destroy' or
	// `outOfService') it must be first unreferenced
	// from all associated lines.
	// If the implementator of this MIB has chosen not
	// to implement `dynamic assignment' of profiles, this
	// object's MIN-ACCESS is read-only and its value
	// is always to be `active'.
	AdslLineAlarmConfProfileRowStatus uint `snmp:"1.3.6.1.2.1.10.94.1.1.15.1.20" snmpType:"enum" snmpEnum:"RowStatusMap"`
}

// Table: adslLineConfProfileTable (1.3.6.1.2.1.10.94.1.1.14)
// This table contains information on the ADSL line
// configuration.  One entry in this table reflects a
// profile defined by a manager which can be used to
// configure the ADSL line.
type AdslLineConfProfileTable struct {
	Entries map[string]AdslLineConfProfileEntry `snmp:"1.3.6.1.2.1.10.94.1.1.14.1"`
}

// Entry: adslLineConfProfileEntry (1.3.6.1.2.1.10.94.1.1.14.1)
// Each entry consists of a list of parameters that
// represents the configuration of an ADSL modem.
// When `dynamic' profiles are implemented, a default
// profile will always exist.  This profile's name will
// be set to `DEFVAL' and its parameters will be set
// to vendor specific values, unless otherwise specified
// in this document.
// When `static' profiles are implemented, profiles
// are automaticly created or destroyed as ADSL
// physical lines are discovered and removed by
// the system.  The name of the profile will be
// equivalent to the decimal value of the line's
// interface index.
type AdslLineConfProfileEntry struct {
	// Configured Maximum Transmit rate for `Fast' channels,
	// in bps.  See adslAtucConfRateChanRatio for information
	// regarding RADSL mode and see ATUR transmit rate for
	// ATUC receive rates.
	AdslAtucChanConfFastMaxTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.13"`
	// Configured Minimum Transmit rate for `Fast' channels,
	// in bps.  See adslAtucConfRateChanRatio for information
	// regarding RADSL mode and ATUR transmit rate for
	// ATUC receive rates.
	AdslAtucChanConfFastMinTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.11"`
	// Configured Maximum Transmit rate for `Interleave'
	// channels, in bps.  See adslAtucConfRateChanRatio for
	// information regarding RADSL mode and ATUR transmit
	// rate for ATUC receive rates.
	AdslAtucChanConfInterleaveMaxTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.14"`
	// Configured Minimum Transmit rate for `Interleave'
	// channels, in bps.  See adslAtucConfRateChanRatio for
	// information regarding RADSL mode and see
	// ATUR transmit rate for receive rates.
	AdslAtucChanConfInterleaveMinTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.12"`
	// Configured maximum Interleave Delay for this channel.
	// Interleave delay applies only to the interleave channel
	// and defines the mapping (relative spacing) between
	// subsequent input bytes at the interleaver input and
	// their placement in the bit stream at the interleaver
	// output.  Larger numbers provide greater separation
	// between consecutive input bytes in the output bit
	// stream allowing for improved impulse noise immunity
	// at the expense of payload latency.
	AdslAtucChanConfMaxInterleaveDelay uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.15"`
	// Configured Signal/Noise Margin for rate downshift.
	// If the noise margin falls below this level, the modem
	// should attempt to decrease its transmit rate.  In
	// the case that RADSL mode is not present,
	// the value will be `0'.
	AdslAtucConfDownshiftSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.7"`
	// Configured Maximum acceptable Signal/Noise Margin.
	// If the Noise Margin is above this the modem should
	// attempt to reduce its power output to optimize its
	// operation.
	AdslAtucConfMaxSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.5"`
	// Minimum time that the current margin is below
	// DownshiftSnrMgn before a downshift occurs.
	// In the case that RADSL mode is not present,
	// the value will be `0'.
	AdslAtucConfMinDownshiftTime uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.10"`
	// Configured Minimum acceptable Signal/Noise Margin.
	// If the noise margin falls below this level, the modem
	// should attempt to increase its power output.  If that
	// is not possible the modem will attempt to
	// re-initialize or shut down.
	AdslAtucConfMinSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.6"`
	// Minimum time that the current margin is above
	// UpshiftSnrMgn before an upshift occurs.
	// In the case that RADSL is not present, the value will
	// be `0'.
	AdslAtucConfMinUpshiftTime uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.9"`
	// Configured allocation ratio of excess transmit
	// bandwidth between fast and interleaved channels.  Only
	// applies when two channel mode and RADSL are supported.
	// Distribute bandwidth on each channel in excess of the
	// corresponding ChanConfMinTxRate so that:
	// adslAtucConfRateChanRatio =
	// [Fast / (Fast + Interleaved)] * 100
	// In other words this value is the fast channel
	// percentage.
	AdslAtucConfRateChanRatio uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.3"`
	// Defines what form of transmit rate adaptation is
	// configured on this modem.  See ADSL Forum TR-005 [3]
	// for more information.
	AdslAtucConfRateMode uint `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.2" snmpType:"enum" snmpEnum:"EnumerationMap"`
	// Configured Target Signal/Noise Margin.
	// This is the Noise Margin the modem must achieve
	// with a BER of 10-7 or better to successfully complete
	// initialization.
	AdslAtucConfTargetSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.4"`
	// Configured Signal/Noise Margin for rate upshift.
	// If the noise margin rises above this level, the modem
	// should attempt to increase its transmit rate.    In
	// the case that RADSL is not present, the value will
	// be `0'.
	AdslAtucConfUpshiftSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.8"`
	// Configured Maximum Transmit rate for `Fast' channels,
	// in bps.  See adslAturConfRateChanRatio for information
	// regarding RADSL mode and ATUC transmit rate
	// for ATUR receive rates.
	AdslAturChanConfFastMaxTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.27"`
	// Configured Minimum Transmit rate for `Fast' channels,
	// in bps.  See adslAturConfRateChanRatio for information
	// regarding RADSL mode and ATUC transmit rate
	// for ATUR receive rates.
	AdslAturChanConfFastMinTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.25"`
	// Configured Maximum Transmit rate for `Interleave'
	// channels, in bps.  See adslAturConfRateChanRatio for
	// information regarding RADSL mode and see
	// ATUC transmit rate for ATUR receive rates.
	AdslAturChanConfInterleaveMaxTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.28"`
	// Configured Minimum Transmit rate for `Interleave'
	// channels, in bps.  See adslAturConfRateChanRatio for
	// information regarding RADSL mode and ATUC transmit rate
	// for ATUR receive rates.
	AdslAturChanConfInterleaveMinTxRate uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.26"`
	// Configured maximum Interleave Delay for this channel.
	// Interleave delay applies only to the interleave channel
	// and defines the mapping (relative spacing) between
	// subsequent input bytes at the interleaver input and
	// their placement in the bit stream at the interleaver
	// output.  Larger numbers provide greater separation
	// between consecutive input bytes in the output bit
	// stream allowing for improved impulse noise immunity
	// at the expense of payload latency.
	AdslAturChanConfMaxInterleaveDelay uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.29"`
	// Configured Signal/Noise Margin for rate downshift.
	// If the noise margin falls below this level, the modem
	// should attempt to decrease its transmit rate.
	// In the case that RADSL mode is not present,
	// the value will be `0'.
	AdslAturConfDownshiftSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.21"`
	// Configured Maximum acceptable Signal/Noise Margin.
	// If the Noise Margin is above this the modem should
	// attempt to reduce its power output to optimize its
	// operation.
	AdslAturConfMaxSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.19"`
	// Minimum time that the current margin is below
	// DownshiftSnrMgn before a downshift occurs.
	// In the case that RADSL mode is not present,
	// the value will be `0'.
	AdslAturConfMinDownshiftTime uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.24"`
	// Configured Minimum acceptable Signal/Noise Margin.
	// If the noise margin falls below this level, the modem
	// should attempt to increase its power output.  If that
	// is not possible the modem will attempt to
	// re-initialize or shut down.
	AdslAturConfMinSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.20"`
	// Minimum time that the current margin is above
	// UpshiftSnrMgn before an upshift occurs.
	// In the case that RADSL is not present, the value will
	// be `0'.
	AdslAturConfMinUpshiftTime uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.23"`
	// Configured allocation ratio of excess transmit
	// bandwidth between fast and interleaved channels.  Only
	// applies when two channel mode and RADSL are supported.
	// Distribute bandwidth on each channel in excess of the
	// corresponding ChanConfMinTxRate so that:
	// adslAturConfRateChanRatio =
	// [Fast / (Fast + Interleaved)] * 100
	// In other words this value is the fast channel
	// percentage.
	AdslAturConfRateChanRatio uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.17"`
	// Defines what form of transmit rate adaptation is
	// configured on this modem.  See ADSL Forum TR-005 [3]
	// for more information.
	AdslAturConfRateMode uint `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.16" snmpType:"enum" snmpEnum:"EnumerationMap"`
	// Configured Target Signal/Noise Margin.
	// This is the Noise Margin the modem must achieve
	// with a BER of 10-7 or better to successfully complete
	// initialization.
	AdslAturConfTargetSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.18"`
	// Configured Signal/Noise Margin for rate upshift.
	// If the noise margin rises above this level, the modem
	// should attempt to increase its transmit rate.
	// In the case that RADSL is not present,
	// the value will be `0'.
	AdslAturConfUpshiftSnrMgn uint32 `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.22"`
	// This object is used by the line configuration table
	// in order to identify a row of this table.
	// When `dynamic' profiles are implemented, the profile
	// name is user specified.  Also, the system will always
	// provide a default profile whose name is `DEFVAL'.
	// When `static' profiles are implemented, there is an
	// one-to-one relationship between each line and its
	// profile.  In which case, the profile name will
	// need to algorithmicly represent the Line's ifIndex.
	// Therefore, the profile's name is a decimalized string
	// of the ifIndex that is fixed-length (i.e., 10) with
	// leading zero(s).  For example, the profile name for
	// ifIndex which equals '15' will be '0000000015'.
	AdslLineConfProfileName string `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.1" snmpType:"octet-string"`
	// This object is used to create a new row or modify or
	// delete an existing row in this table.
	// A profile activated by setting this object to
	// `active'.  When `active' is set, the system
	// will validate the profile.
	// Before a profile can be deleted or taken out of
	// service, (by setting this object to `destroy' or
	// `outOfService') it must be first unreferenced
	// from all associated lines.
	// If the implementator of this MIB has chosen not
	// to implement `dynamic assignment' of profiles, this
	// object's MIN-ACCESS is read-only and its value
	// is always to be `active'.
	AdslLineConfProfileRowStatus uint `snmp:"1.3.6.1.2.1.10.94.1.1.14.1.30" snmpType:"enum" snmpEnum:"RowStatusMap"`
}

// Table: adslLineTable (1.3.6.1.2.1.10.94.1.1.1)
// This table includes common attributes describing
// both ends of the line.  It is required for all ADSL
// physical interfaces.  ADSL physical interfaces are
// those ifEntries where ifType is equal to adsl(94).
type AdslLineTable struct {
	Entries map[string]AdslLineEntry `snmp:"1.3.6.1.2.1.10.94.1.1.1.1"`
}

// Entry: adslLineEntry (1.3.6.1.2.1.10.94.1.1.1.1)
// An entry in adslLineTable.
type AdslLineEntry struct {
	// The value of this object identifies the row
	// in the ADSL Line Alarm Configuration Profile Table,
	// (adslLineAlarmConfProfileTable), which applies to this
	// ADSL line, and channels if applicable.
	// For `dynamic' mode, in the case which the
	// alarm profile has not been set, the
	// value will be set to `DEFVAL'.
	// If the implementator of this MIB has chosen not
	// to implement `dynamic assignment' of profiles, this
	// object's MIN-ACCESS is read-only.
	AdslLineAlarmConfProfile string `snmp:"1.3.6.1.2.1.10.94.1.1.1.1.5" snmpType:"octet-string"`
	// Specifies the ADSL coding type used on this
	// line.
	AdslLineCoding uint `snmp:"1.3.6.1.2.1.10.94.1.1.1.1.1" snmpType:"enum" snmpEnum:"AdslLineCodingTypeMap"`
	// The value of this object identifies the row
	// in the ADSL Line Configuration Profile Table,
	// (adslLineConfProfileTable), which applies for this
	// ADSL line, and channels if applicable.
	// For `dynamic' mode, in the case which the
	// configuration profile has not been set, the
	// value will be set to `DEFVAL'.
	// If the implementator of this MIB has chosen not
	// to implement `dynamic assignment' of profiles, this
	// object's MIN-ACCESS is read-only.
	AdslLineConfProfile string `snmp:"1.3.6.1.2.1.10.94.1.1.1.1.4" snmpType:"octet-string"`
	// OID instance in vendor-specific MIB. The Instance may
	// be used to determine shelf/slot/port of the ATUC
	// interface in a DSLAM.
	AdslLineSpecific string `snmp:"1.3.6.1.2.1.10.94.1.1.1.1.3" snmpType:"object-identifier"`
	// Defines the type of ADSL physical line
	// entity that exists, by defining whether and how
	// the line is channelized.  If the line is channelized,
	// the value will be other than noChannel(1).  This
	// object defines which channel type(s) are supported.
	// In the case that the line is channelized, the manager
	// can use the ifStackTable to determine the ifIndex for
	// the associated channel(s).
	AdslLineType uint `snmp:"1.3.6.1.2.1.10.94.1.1.1.1.2" snmpType:"enum" snmpEnum:"EnumerationMap"`
}

// This data type is used as the syntax for the ADSL
// Line Code.
var AdslLineCodingTypeMap = snmp.StringMap{
	0: "other",
	1: "dmt",
	2: "cap",
	3: "qam",
}

var BitsMap = snmp.StringMap{
	0: "noDefect",
	1: "lossOfFraming",
	2: "lossOfSignal",
	3: "lossOfPower",
	4: "lossOfSignalQuality",
}

var EnumerationMap = snmp.StringMap{
	0: "enable",
	1: "disable",
}

// The RowStatus textual convention is used to manage the
// creation and deletion of conceptual rows, and is used as the
// value of the SYNTAX clause for the status column of a
// conceptual row (as described in Section 7.7.1 of [2].)
// The status column has six defined values:
// - `active', which indicates that the conceptual row is
// available for use by the managed device;
// - `notInService', which indicates that the conceptual
// row exists in the agent, but is unavailable for use by
// the managed device (see NOTE below); 'notInService' has
// no implication regarding the internal consistency of
// the row, availability of resources, or consistency with
// the current state of the managed device;
// - `notReady', which indicates that the conceptual row
// exists in the agent, but is missing information
// necessary in order to be available for use by the
// managed device (i.e., one or more required columns in
// the conceptual row have not been instanciated);
// - `createAndGo', which is supplied by a management
// station wishing to create a new instance of a
// conceptual row and to have its status automatically set
// to active, making it available for use by the managed
// device;
// - `createAndWait', which is supplied by a management
// station wishing to create a new instance of a
// conceptual row (but not make it available for use by
// the managed device); and,
// - `destroy', which is supplied by a management station
// wishing to delete all of the instances associated with
// an existing conceptual row.
// Whereas five of the six values (all except `notReady') may
// be specified in a management protocol set operation, only
// three values will be returned in response to a management
// protocol retrieval operation:  `notReady', `notInService' or
// `active'.  That is, when queried, an existing conceptual row
// has only three states:  it is either available for use by
// the managed device (the status column has value `active');
// it is not available for use by the managed device, though
// the agent has sufficient information to attempt to make it
// so (the status column has value `notInService'); or, it is
// not available for use by the managed device, and an attempt
// to make it so would fail because the agent has insufficient
// information (the state column has value `notReady').
// NOTE WELL
// This textual convention may be used for a MIB table,
// irrespective of whether the values of that table's
// conceptual rows are able to be modified while it is
// active, or whether its conceptual rows must be taken
// out of service in order to be modified.  That is, it is
// the responsibility of the DESCRIPTION clause of the
// status column to specify whether the status column must
// not be `active' in order for the value of some other
// column of the same conceptual row to be modified.  If
// such a specification is made, affected columns may be
// changed by an SNMP set PDU if the RowStatus would not
// be equal to `active' either immediately before or after
// processing the PDU.  In other words, if the PDU also
// contained a varbind that would change the RowStatus
// value, the column in question may be changed if the
// RowStatus was not equal to `active' as the PDU was
// received, or if the varbind sets the status to a value
// other than 'active'.
// Also note that whenever any elements of a row exist, the
// RowStatus column must also exist.
// To summarize the effect of having a conceptual row with a
// status column having a SYNTAX clause value of RowStatus,
// consider the following state diagram:
// STATE
// +--------------+-----------+-------------+-------------
// |      A       |     B     |      C      |      D
// |              |status col.|status column|
// |status column |    is     |      is     |status column
// ACTION    |does not exist|  notReady | notInService|  is active
// --------------+--------------+-----------+-------------+-------------
// set status    |noError    ->D|inconsist- |inconsistent-|inconsistent-
// column to     |       or     |   entValue|        Value|        Value
// createAndGo   |inconsistent- |           |             |
// |         Value|           |             |
// --------------+--------------+-----------+-------------+-------------
// set status    |noError  see 1|inconsist- |inconsistent-|inconsistent-
// column to     |       or     |   entValue|        Value|        Value
// createAndWait |wrongValue    |           |             |
// --------------+--------------+-----------+-------------+-------------
// set status    |inconsistent- |inconsist- |noError      |noError
// column to     |         Value|   entValue|             |
// active        |              |           |             |
// |              |     or    |             |
// |              |           |             |
// |              |see 2   ->D|see 8     ->D|          ->D
// --------------+--------------+-----------+-------------+-------------
// set status    |inconsistent- |inconsist- |noError      |noError   ->C
// column to     |         Value|   entValue|             |
// notInService  |              |           |             |
// |              |     or    |             |      or
// |              |           |             |
// |              |see 3   ->C|          ->C|see 6
// --------------+--------------+-----------+-------------+-------------
// set status    |noError       |noError    |noError      |noError   ->A
// column to     |              |           |             |      or
// destroy       |           ->A|        ->A|          ->A|see 7
// --------------+--------------+-----------+-------------+-------------
// set any other |see 4         |noError    |noError      |see 5
// column to some|              |           |             |
// value         |              |      see 1|          ->C|          ->D
// --------------+--------------+-----------+-------------+-------------
// (1) goto B or C, depending on information available to the
// agent.
// (2) if other variable bindings included in the same PDU,
// provide values for all columns which are missing but
// required, and all columns have acceptable values, then
// return noError and goto D.
// (3) if other variable bindings included in the same PDU,
// provide legal values for all columns which are missing but
// required, then return noError and goto C.
// (4) at the discretion of the agent, the return value may be
// either:
// inconsistentName:  because the agent does not choose to
// create such an instance when the corresponding
// RowStatus instance does not exist, or
// inconsistentValue:  if the supplied value is
// inconsistent with the state of some other MIB object's
// value, or
// noError: because the agent chooses to create the
// instance.
// If noError is returned, then the instance of the status
// column must also be created, and the new state is B or C,
// depending on the information available to the agent.  If
// inconsistentName or inconsistentValue is returned, the row
// remains in state A.
// (5) depending on the MIB definition for the column/table,
// either noError or inconsistentValue may be returned.
// (6) the return value can indicate one of the following
// errors:
// wrongValue: because the agent does not support
// notInService (e.g., an agent which does not support
// createAndWait), or
// inconsistentValue: because the agent is unable to take
// the row out of service at this time, perhaps because it
// is in use and cannot be de-activated.
// (7) the return value can indicate the following error:
// inconsistentValue: because the agent is unable to
// remove the row at this time, perhaps because it is in
// use and cannot be de-activated.
// (8) the transition to D can fail, e.g., if the values of the
// conceptual row are inconsistent, then the error code would
// be inconsistentValue.
// NOTE: Other processing of (this and other varbinds of) the
// set request may result in a response other than noError
// being returned, e.g., wrongValue, noCreation, etc.
// Conceptual Row Creation
// There are four potential interactions when creating a
// conceptual row:  selecting an instance-identifier which is
// not in use; creating the conceptual row; initializing any
// objects for which the agent does not supply a default; and,
// making the conceptual row available for use by the managed
// device.
// Interaction 1: Selecting an Instance-Identifier
// The algorithm used to select an instance-identifier varies
// for each conceptual row.  In some cases, the instance-
// identifier is semantically significant, e.g., the
// destination address of a route, and a management station
// selects the instance-identifier according to the semantics.
// In other cases, the instance-identifier is used solely to
// distinguish conceptual rows, and a management station
// without specific knowledge of the conceptual row might
// examine the instances present in order to determine an
// unused instance-identifier.  (This approach may be used, but
// it is often highly sub-optimal; however, it is also a
// questionable practice for a naive management station to
// attempt conceptual row creation.)
// Alternately, the MIB module which defines the conceptual row
// might provide one or more objects which provide assistance
// in determining an unused instance-identifier.  For example,
// if the conceptual row is indexed by an integer-value, then
// an object having an integer-valued SYNTAX clause might be
// defined for such a purpose, allowing a management station to
// issue a management protocol retrieval operation.  In order
// to avoid unnecessary collisions between competing management
// stations, `adjacent' retrievals of this object should be
// different.
// Finally, the management station could select a pseudo-random
// number to use as the index.  In the event that this index
// was already in use and an inconsistentValue was returned in
// response to the management protocol set operation, the
// management station should simply select a new pseudo-random
// number and retry the operation.
// A MIB designer should choose between the two latter
// algorithms based on the size of the table (and therefore the
// efficiency of each algorithm).  For tables in which a large
// number of entries are expected, it is recommended that a MIB
// object be defined that returns an acceptable index for
// creation.  For tables with small numbers of entries, it is
// recommended that the latter pseudo-random index mechanism be
// used.
// Interaction 2: Creating the Conceptual Row
// Once an unused instance-identifier has been selected, the
// management station determines if it wishes to create and
// activate the conceptual row in one transaction or in a
// negotiated set of interactions.
// Interaction 2a: Creating and Activating the Conceptual Row
// The management station must first determine the column
// requirements, i.e., it must determine those columns for
// which it must or must not provide values.  Depending on the
// complexity of the table and the management station's
// knowledge of the agent's capabilities, this determination
// can be made locally by the management station.  Alternately,
// the management station issues a management protocol get
// operation to examine all columns in the conceptual row that
// it wishes to create.  In response, for each column, there
// are three possible outcomes:
// - a value is returned, indicating that some other
// management station has already created this conceptual
// row.  We return to interaction 1.
// - the exception `noSuchInstance' is returned,
// indicating that the agent implements the object-type
// associated with this column, and that this column in at
// least one conceptual row would be accessible in the MIB
// view used by the retrieval were it to exist. For those
// columns to which the agent provides read-create access,
// the `noSuchInstance' exception tells the management
// station that it should supply a value for this column
// when the conceptual row is to be created.
// - the exception `noSuchObject' is returned, indicating
// that the agent does not implement the object-type
// associated with this column or that there is no
// conceptual row for which this column would be
// accessible in the MIB view used by the retrieval.  As
// such, the management station can not issue any
// management protocol set operations to create an
// instance of this column.
// Once the column requirements have been determined, a
// management protocol set operation is accordingly issued.
// This operation also sets the new instance of the status
// column to `createAndGo'.
// When the agent processes the set operation, it verifies that
// it has sufficient information to make the conceptual row
// available for use by the managed device.  The information
// available to the agent is provided by two sources:  the
// management protocol set operation which creates the
// conceptual row, and, implementation-specific defaults
// supplied by the agent (note that an agent must provide
// implementation-specific defaults for at least those objects
// which it implements as read-only).  If there is sufficient
// information available, then the conceptual row is created, a
// `noError' response is returned, the status column is set to
// `active', and no further interactions are necessary (i.e.,
// interactions 3 and 4 are skipped).  If there is insufficient
// information, then the conceptual row is not created, and the
// set operation fails with an error of `inconsistentValue'.
// On this error, the management station can issue a management
// protocol retrieval operation to determine if this was
// because it failed to specify a value for a required column,
// or, because the selected instance of the status column
// already existed.  In the latter case, we return to
// interaction 1.  In the former case, the management station
// can re-issue the set operation with the additional
// information, or begin interaction 2 again using
// `createAndWait' in order to negotiate creation of the
// conceptual row.
// NOTE WELL
// Regardless of the method used to determine the column
// requirements, it is possible that the management
// station might deem a column necessary when, in fact,
// the agent will not allow that particular columnar
// instance to be created or written.  In this case, the
// management protocol set operation will fail with an
// error such as `noCreation' or `notWritable'.  In this
// case, the management station decides whether it needs
// to be able to set a value for that particular columnar
// instance.  If not, the management station re-issues the
// management protocol set operation, but without setting
// a value for that particular columnar instance;
// otherwise, the management station aborts the row
// creation algorithm.
// Interaction 2b: Negotiating the Creation of the Conceptual
// Row
// The management station issues a management protocol set
// operation which sets the desired instance of the status
// column to `createAndWait'.  If the agent is unwilling to
// process a request of this sort, the set operation fails with
// an error of `wrongValue'.  (As a consequence, such an agent
// must be prepared to accept a single management protocol set
// operation, i.e., interaction 2a above, containing all of the
// columns indicated by its column requirements.)  Otherwise,
// the conceptual row is created, a `noError' response is
// returned, and the status column is immediately set to either
// `notInService' or `notReady', depending on whether it has
// sufficient information to (attempt to) make the conceptual
// row available for use by the managed device.  If there is
// sufficient information available, then the status column is
// set to `notInService'; otherwise, if there is insufficient
// information, then the status column is set to `notReady'.
// Regardless, we proceed to interaction 3.
// Interaction 3: Initializing non-defaulted Objects
// The management station must now determine the column
// requirements.  It issues a management protocol get operation
// to examine all columns in the created conceptual row.  In
// the response, for each column, there are three possible
// outcomes:
// - a value is returned, indicating that the agent
// implements the object-type associated with this column
// and had sufficient information to provide a value.  For
// those columns to which the agent provides read-create
// access (and for which the agent allows their values to
// be changed after their creation), a value return tells
// the management station that it may issue additional
// management protocol set operations, if it desires, in
// order to change the value associated with this column.
// - the exception `noSuchInstance' is returned,
// indicating that the agent implements the object-type
// associated with this column, and that this column in at
// least one conceptual row would be accessible in the MIB
// view used by the retrieval were it to exist. However,
// the agent does not have sufficient information to
// provide a value, and until a value is provided, the
// conceptual row may not be made available for use by the
// managed device.  For those columns to which the agent
// provides read-create access, the `noSuchInstance'
// exception tells the management station that it must
// issue additional management protocol set operations, in
// order to provide a value associated with this column.
// - the exception `noSuchObject' is returned, indicating
// that the agent does not implement the object-type
// associated with this column or that there is no
// conceptual row for which this column would be
// accessible in the MIB view used by the retrieval.  As
// such, the management station can not issue any
// management protocol set operations to create an
// instance of this column.
// If the value associated with the status column is
// `notReady', then the management station must first deal with
// all `noSuchInstance' columns, if any.  Having done so, the
// value of the status column becomes `notInService', and we
// proceed to interaction 4.
// Interaction 4: Making the Conceptual Row Available
// Once the management station is satisfied with the values
// associated with the columns of the conceptual row, it issues
// a management protocol set operation to set the status column
// to `active'.  If the agent has sufficient information to
// make the conceptual row available for use by the managed
// device, the management protocol set operation succeeds (a
// `noError' response is returned).  Otherwise, the management
// protocol set operation fails with an error of
// `inconsistentValue'.
// NOTE WELL
// A conceptual row having a status column with value
// `notInService' or `notReady' is unavailable to the
// managed device.  As such, it is possible for the
// managed device to create its own instances during the
// time between the management protocol set operation
// which sets the status column to `createAndWait' and the
// management protocol set operation which sets the status
// column to `active'.  In this case, when the management
// protocol set operation is issued to set the status
// column to `active', the values held in the agent
// supersede those used by the managed device.
// If the management station is prevented from setting the
// status column to `active' (e.g., due to management station
// or network failure) the conceptual row will be left in the
// `notInService' or `notReady' state, consuming resources
// indefinitely.  The agent must detect conceptual rows that
// have been in either state for an abnormally long period of
// time and remove them.  It is the responsibility of the
// DESCRIPTION clause of the status column to indicate what an
// abnormally long period of time would be.  This period of
// time should be long enough to allow for human response time
// (including `think time') between the creation of the
// conceptual row and the setting of the status to `active'.
// In the absence of such information in the DESCRIPTION
// clause, it is suggested that this period be approximately 5
// minutes in length.  This removal action applies not only to
// newly-created rows, but also to previously active rows which
// are set to, and left in, the notInService state for a
// prolonged period exceeding that which is considered normal
// for such a conceptual row.
// Conceptual Row Suspension
// When a conceptual row is `active', the management station
// may issue a management protocol set operation which sets the
// instance of the status column to `notInService'.  If the
// agent is unwilling to do so, the set operation fails with an
// error of `wrongValue' or `inconsistentValue'.  Otherwise,
// the conceptual row is taken out of service, and a `noError'
// response is returned.  It is the responsibility of the
// DESCRIPTION clause of the status column to indicate under
// what circumstances the status column should be taken out of
// service (e.g., in order for the value of some other column
// of the same conceptual row to be modified).
// Conceptual Row Deletion
// For deletion of conceptual rows, a management protocol set
// operation is issued which sets the instance of the status
// column to `destroy'.  This request may be made regardless of
// the current value of the status column (e.g., it is possible
// to delete conceptual rows which are either `notReady',
// `notInService' or `active'.)  If the operation succeeds,
// then all instances associated with the conceptual row are
// immediately removed.
var RowStatusMap = snmp.StringMap{
	0: "active",
	1: "notInService",
	2: "notReady",
	3: "createAndGo",
	4: "createAndWait",
	5: "destroy",
}

// Represents a boolean value.
var TruthValueMap = snmp.StringMap{
	0: "true",
	1: "false",
}
