package main

import (
	"flag"
	"fmt"
	"maps"
	"os"
	"os/exec"
	"reflect"
	"regexp"
	"slices"
	"strings"

	"github.com/sleepinggenius2/gosmi"
	smit "github.com/sleepinggenius2/gosmi/types"
)

var reNewLine = regexp.MustCompile(`\n`)

func main() {
	var (
		modules     arrayStrings
		paths       arrayStrings
		packageName string
		outputFile  string
	)

	flag.Var(&modules, "m", "Module to load")
	flag.Var(&paths, "p", "Path to add")
	flag.StringVar(&packageName, "P", "unknown", "Package name")
	flag.StringVar(&outputFile, "o", "generated.go", "Output file")
	flag.Parse()

	err, loaded := initSMI(paths, modules)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}

	// Init output code
	outputData := fmt.Sprintf(`// Code generated by "mib_generator %s". DO NOT EDIT`, strings.Join(os.Args[1:], " "))
	outputData += "\n\npackage " + packageName + "\n\n"

	outputData += "import \"github.com/lazyfrosch/dslmodem_exporter/pkg/snmp\"\n\n"

	var errors uint
	for _, mib := range loaded {
		err, extraOutput := generateMIB(mib)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %s\n", err)
			errors++
		}
		outputData += extraOutput
	}
	if errors > 0 {
		os.Exit(1)
	}

	// Write data to file
	os.WriteFile(outputFile, []byte(outputData), 0644)

	// Call go fmt on written file
	err = exec.Command("go", "fmt", outputFile).Run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "go fmt failed: %s\n", err)
		os.Exit(1)
	}
}

func Exit() {
	gosmi.Exit()
}

func initSMI(paths, modules []string) (error, []string) {
	gosmi.Init()

	for _, path := range paths {
		gosmi.AppendPath(path)
	}

	var loaded []string
	for _, module := range modules {
		moduleName, err := gosmi.LoadModule(module)
		if err != nil {
			return fmt.Errorf("Init error: %w", err), nil
		}

		fmt.Fprintf(os.Stderr, "Loaded module %s\n", moduleName)
		loaded = append(loaded, moduleName)
	}

	return nil, loaded
}

func generateMIB(mib string) (err error, output string) {
	m, err := gosmi.GetModule(mib)
	if err != nil {
		err = fmt.Errorf("Could not load module: %w", err)
		return
	}

	fmt.Fprintf(os.Stderr, "Generating MIB %s\n", mib)

	output += commentText(m.Name, "")

	// Store found types
	foundEnums := map[string]gosmi.SmiType{}
	foundTables := map[string]gosmi.Table{}

	// Scan nodes and write the un-sequenced ones as const
	output += "const (\n"
	firstConst := true
	for _, node := range m.GetNodes() {
		// Check node kinds
		switch node.Kind {
		case smit.NodeTable:
			// New Table found, add it to the list
			foundTables[node.Name] = node.AsTable()
			// we don't skip the rest, we want to write the OID const

		case smit.NodeGroup, smit.NodeCompliance, smit.NodeNotification:
			// we don't really care about these types
			continue
		}

		// Check if this is a enum and remember it
		if node.SmiType != nil && node.SmiType.Enum != nil {
			foundEnums[node.SmiType.Name] = *node.SmiType
		}

		if node.Kind == smit.NodeRow || node.Kind == smit.NodeColumn {
			// skip because it is part of the table
			continue
		}

		if description := commentText(node.Description, "\t"); description != "" {
			if !firstConst {
				output += "\n"
			} else {
				firstConst = false
			}
			output += description
		}

		output += "\t" + exportableName(node.Name) + "Oid = \"" + node.Oid.String() + "\"\n"
	}
	output += ")\n"

	// Write all tables
	for _, name := range slices.Sorted(maps.Keys(foundTables)) {
		tableName := exportableName(name)
		table := foundTables[name]
		entry := table.GetRow()

		// Write table struct
		output += "\n"
		output += commentText(fmt.Sprintf("Table: %s (%s)", name, table.Oid.String()), "")
		output += commentText(table.Description, "")
		output += "type " + tableName + " struct {\n"
		output += fmt.Sprintf("\t Entries map[string]%s `snmp:\"%s\"`\n", exportableName(entry.Name), entry.Oid.String())
		output += "}\n"

		// Write entry struct
		output += "\n"
		output += commentText(fmt.Sprintf("Entry: %s (%s)", entry.Name, entry.Oid.String()), "")
		output += commentText(entry.Description, "")
		output += "type " + exportableName(entry.Name) + " struct {\n"
		for _, nodeName := range slices.Sorted(maps.Keys(table.Columns)) {
			node := table.Columns[nodeName]
			output += commentText(node.Description, "")
			nodeType, extraTags := smiToGoType(*node.SmiType)
			output += fmt.Sprintf("\t%s %s `snmp:\"%s\"%s`\n", exportableName(node.Name), nodeType, node.Oid.String(), extraTags)
		}
		output += "}\n"
	}

	// Write all enums
	for _, name := range slices.Sorted(maps.Keys(foundEnums)) {
		mapName := exportableName(name) + "Map"
		smiType := foundEnums[name]

		output += "\n"
		output += commentText(smiType.Reference, "")
		output += commentText(smiType.Description, "")

		output += "var " + mapName + " = snmp.StringMap{\n"
		for i, enum := range smiType.Enum.Values {
			output += "\t" + fmt.Sprintf("%d", i) + ": \"" + enum.Name + "\",\n"
		}
		output += "}\n"
	}

	return
}

func exportableName(name string) string {
	return strings.ToUpper(name[0:1]) + name[1:]
}

func commentText(description, indent string) string {
	if strings.TrimSpace(description) == "" {
		return ""
	}

	description = reNewLine.ReplaceAllString(description, "\n"+indent+"// ")

	return indent + "// " + description + "\n"
}

func smiToGoType(smiType gosmi.SmiType) (typeid string, tags string) {
	typeid = "string" // the fallback default

	switch smiType.BaseType {
	case smit.BaseTypeInteger32:
		typeid = "int32"
	case smit.BaseTypeUnsigned32:
		typeid = "uint32"
	case smit.BaseTypeInteger64:
		typeid = "int64"
	case smit.BaseTypeUnsigned64:
		typeid = "uint64"
	case smit.BaseTypeFloat32:
		typeid = "float32"
	case smit.BaseTypeFloat64:
		typeid = "float64"
	case smit.BaseTypeFloat128:
		typeid = "float128"
	case smit.BaseTypeEnum:
		typeid = "uint"
		tags = " snmpType:\"enum\""
		tags += " snmpEnum:\"" + exportableName(smiType.Name) + "Map" + "\""
	case smit.BaseTypeBits:
		typeid = "uint"
	case smit.BaseTypePointer:
		tags = " snmpType:\"pointer\""
		// Not sure how to implement an actual type for this
	case smit.BaseTypeUnknown:
		tags = " snmpType:\"unknown\""
	case smit.BaseTypeOctetString:
		tags = " snmpType:\"octet-string\""
	case smit.BaseTypeObjectIdentifier:
		tags = " snmpType:\"object-identifier\""
	default:
		tags = " snmpType:\"" + reflect.TypeOf(smiType.BaseType).String() + "\""
	}

	return
}
